api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "cpp-cart-transformer"
type = "function"

description = "t:description"

[[extensions.targeting]]
target = "purchase.cart-transform.run"
input_query = "src/run.graphql"
# export = "run"

[extensions.build]
command = "npm run build"
path = "dist/optimized.wasm"

[extensions.ui.paths]
create = "/"
details = "/"
