# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d85a4d5a2e613af39ac2496229bda680"
name = "andre-dev-app"
handle = "andre-dev-app"
application_url = "https://thick-sri-laws-intervals.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bc-andre-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://thick-sri-laws-intervals.trycloudflare.com/auth/callback",
  "https://thick-sri-laws-intervals.trycloudflare.com/auth/shopify/callback",
  "https://thick-sri-laws-intervals.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
